apiVersion: apps/v1
kind: Deployment
metadata:
  name: profileservice
  namespace: ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: profileservice
  template:
    metadata:
      labels:
        app: profileservice
    spec:
      containers:
      - name: profileservice
        image: prasannaacr.azurecr.io/profileservice:v1
        ports:
        - containerPort: 3002
        env:
        - name: MONGO_URL
          valueFrom:
            secretKeyRef:
              name: profile-secret
              key: MONGO_URL
